#!/bin/bash
echo "#ifndef MAIN_H
#define MAIN_H

#include <stdio.h>
#include <math.h>
#include <string.h>
#include <time.h>
#include <strings.h>
#include <stdlib.h>
#include <ctype.h>


int conditional(void);
int betty_stile_included(void);
int to_edit(void);
int edit(void);

#endif" >> $1
