#!/bin/bash

echo "#include <stdlib.h>
#include <time.h>
#include <stdio.h>


/**
 * main - Entry point
 *
 * Description: print value of n satus; zero, positive or negative
 *
 * Return: Always 0 (Success)
*/

int main(void)
{
	printf("this is a module");
	return (0);
}" >> $1
